Flutter - iOS - ImagePicker support below iOS 14 version
doo/scanbot-sdk-example-flutter pull request #36
Opened 2022-02-22 10:19 UTC by scan-mayank

- [x] Added Native iOS GMImagePicker v 0.0.2 third party pod library for image picker support below iOS 14 to the Runner project
- [x] Created PlatformChannel in example project for using old iOS version picker
- [x] Model class for image picker path response
- [x] Platform helper class to consume the native service channels
- [x] Added permission in info.plist iOS
- [x] Created Native channel method for checking iOS version below 14

2022-03-01 12:04 UTC, marcosaia1812 requested changes

2022-03-01 12:04 UTC, marcosaia1812 commented on ios/Runner/GMImagePickerHelper.swift
> +                    print("This method is called")
Please remove debug prints

2022-03-01 12:04 UTC, marcosaia1812 commented on lib/main.dart
> +      print("The main method is executed");
Please remove debug prints

2022-03-01 12:04 UTC, marcosaia1812 commented on lib/utility/platform_helper.dart
> +      print("Result is:");
Please remove debug prints

2022-03-01 12:53 UTC, scan-mayank commented on ios/Runner/GMImagePickerHelper.swift
> +                    print("This method is called")
Roger that

2022-03-01 12:57 UTC, scan-mayank commented
@marcosaia1812  I have updated the PR by expected changes(removing the debug logs)

2022-03-15 09:25 UTC, marcosaia1812 approved these changes

2022-03-15 09:28 UTC, merged