v.5.1.0 alpha
doo/scanbot-sdk-example-flutter pull request #90
Opened 2024-07-12 16:56 UTC by 4BooM04

2024-08-19 10:11 UTC, 4BooM04 commented on lib/doc_code_sinppet/barcode_sdk/ar_overlay_usecase_snippet.dart
> +        onPressed: _startBarcodeScanner,
Can we make simple button instead of FAB?

2024-08-19 10:32 UTC, 4BooM04 commented on lib/doc_code_sinppet/barcode_sdk/top_bar_config_snippet.dart
> +  // Configure other parameters as needed.
shouldnt we add ? :
```
  var result = await ScanbotSdkUi.startBarcodeScanner(configuration);

    if (result.operationResult == OperationResult.SUCCESS) {
      // TODO: present barcode result as needed
    }
```

2024-08-19 10:33 UTC, 4BooM04 commented on pubspec.yaml
> +    path: ../flutter/scanbot-sdk-flutter/bundle_sdk
switch to QA  version

2024-08-20 10:55 UTC, atacand1920 approved these changes

2024-09-20 09:13 UTC, atacand1920 requested changes

2024-09-20 09:13 UTC, atacand1920 commented on pubspec.yaml
> +  scanbot_sdk: 5.1.0-alpha13
remove alpha tag

2024-09-20 12:12 UTC, atacand1920 approved these changes

2024-09-24 15:49 UTC, atacand1920 approved these changes

2024-09-24 16:19 UTC, merged